name: CI (placeholder)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unity - Placeholder build
        run: echo "This workflow is a placeholder. Add Unity build steps or use unity-ci actions."
